### ISSUE TITLE
Got an unexpected "FILE NOT FOUND " Error

### ISSUE THREAD

**Issue by Sreevardhan12345** [Sheikhlipu123/MultipleGiftCardGenerator-2.0#4]
I just tried to generate some play store gift cards but an unexpected error occured as follows

...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/MultipeGiftCardGenerator-2.0/MultipeGiftCardGenerator 2.0.py", line 434, in <module>
    f = open(total + " Generated.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: '1 Generated.txt'

Can you help me out ....

**Comment by Creepy-Creeper3625** [comment]
I ran the same in pydroid for android and I got no errors. Might be due to a file not in the same directory as the code. Also I am going to be working in your code more and make into a pakage and also add many features. Will pull requests when done. Great concept.

**Comment by Creepy-Creeper3625** [comment]
Change 
`file = total + " generated.txt", "r"` 
to
`file = total + "generated.txt","r"`

**Comment by prolletto64** [comment]
Simply type`touch Generated.txt` in the same directory before executing the script.
In theory should be enough, but idk because i never ran this code on termux.

**Comment by Creepy-Creeper3625** [comment]
@prolletto64 Same issue was raised on pydroid 3 for android. I will run it in repl.it.

**Comment by Creepy-Creeper3625** [comment]
@Sheikhlipu123 We can close this issue now
